export { validatePhone } from './validations/validatePhone';
export { validateEmail } from './validations/validateEmail';
export { validateCep } from './validations/validateCep';
export { validateUF } from './validations/validateUF';
export { validateCNPJ } from './validations/validateCNPJ';
export { validateCPF } from './validations/validateCPF';
export { validateIE } from './validations/ie';
export { validatePIS } from './validations/validatePIS';
export { validateIsEmpty } from './validations/validateIsEmpty';
